name: vector_victor
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0-60.0.dev <3.0.0'

dependencies:
  vector_math: ^2.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
